version: '3.1'
services: 
    keycloak:
        image: quay.io/keycloak/keycloak:15.0.2
        ports: 
            - "9990:9990"
            - "8180:8080"
            - "8444:8443"
        user: root